### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Azie233** [windtail/apt-mirror-check#1]
when i type commond 'apt-mirror-check' in the terminal,i get an error like :
File "/usr/local/lib/python2.7/dist-packages/apt_mirror_check-1.0-py2.7.egg/apt_mirror_check.py", line 113
    yield from bad_files_in_dir(dist_dir, dist_md5attrs(dist_dir))
                  ^
SyntaxError: invalid syntax
can you help to solve it,thx

**Comment by windtail** [comment]
python3 is required, i just update the document
